### ISSUE TITLE
Monotype font for header text example

### ISSUE THREAD

**Issue by jamesdelaneyie** [nathanford/type.js#11]
Slightly odd that the main change you see when you turn on/off type.js is that the monotype font kerning kicks in. Feels weird to use monotype font to show this considering their nature. A dodgy serif might work a little better and be more... _ugh_ 'authentic' forgive that word usage, still pre-coffee

**Comment by nathanford** [comment]
I chose a monospace font because it would have a dramatic change to make it look evenly spaced, and I like the code/type feel of Droid Sans. But I get what you are saying. Any suggestions?

**Comment by jamesdelaneyie** [comment]
No, not particularly. Perhaps a poorly kerned serif from Google's library? Have nothing in mind :)

**Comment by nathanford** [comment]
Cool. I’ll have a think about it. For now, I’m gonna close this.
