### ISSUE TITLE
.editorconfig?

### ISSUE THREAD

**Issue by tomByrer** [nathanford/type.js#16]
I was

  wondering

If you could

  please share

your [`.editorconfig`](http://editorconfig.org/) file.

(

Because

  code with too much vertical . . . . . . . . and horizontal spacing

is hard for me

  to sort in my small mind.

)
;)

**Comment by nathanford** [comment]
This is a good idea, but you’ll have to help me out here. I’ve never used an `.editorconfig` file. How do I set one up?

**Comment by shahzainb** [comment]
I cleaned up the code for you in my PR. I can add an editorconfig file too if you want.

**Comment by shahzainb** [comment]
As an example, paste the following in a .editorconfig file in the root of the repo:

```
# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf

# Javascript
[*.js]
indent_style = space
indent_size = 2
insert_final_newline = true
```

**Comment by nathanford** [comment]
@shahzainb Yeah, I was just looking at the PR. Good stuff! I am going to test and merge in a bit. Feel free to include the .editorconfig.

**Comment by shahzainb** [comment]
I'm at work right now. Will do so when I get back home. :+1:

**Comment by tomByrer** [comment]
Thanks @shahzainb; exactly what I had in mind.  Better chuncked.
