### ISSUE TITLE
externalCSS: true flag triggers second request

### ISSUE THREAD

**Issue by 116-7** [nathanford/type.js#9]
Hi,

I saw your note about how when the "externalCSS" flag is set to true that an extra request is made to get the contents of the linked stylesheets. You can use the document.styleSheets property which is a list of stylesheet objects on the DOM. The cssText property of these objects should contain the string of the CSS. cssText is available in IE9+, Webkit and also Firefox so you may need to fallback if you have to support < IE9 but it should help you not having to re-request the linked stylesheets.

**Comment by darenju** [comment]
Another solution could be to fire a request to a CSS file given as an option to type.js. This file would only contani type.js properties and won't be loaded by the browser. This would prevent browsers from displaying CSS errors such as `no such property`. Problem is: one more CSS file...

**Comment by nathanford** [comment]
@davidjeliba: That’s good news! I hunted around in the sheet object for something that would give me the text... didn’t see that. I’ll give it a try.

@darenju: Good idea! If I can’t get cssText to work, I’ll try this option.

**Comment by nathanford** [comment]
@davidjeliba I looked at `cssText`. It appears to only apply at the element level, rather than at the stylesheet level, and it doesn’t return invalid properties, that I can see. Here is what I tried:

```
var docSheets = document.styleSheets;
for (i in docSheets) {
  console.log(docSheets[i]);
  console.log(docSheets[i].cssText);
}
```

`cssText` returns `undefined`.

**Comment by nathanford** [comment]
On thought I had: if the stylesheet is cached, then there really isn’t a performance hit.

**Comment by geekcubed** [comment]
Each entry in document.styleSheets contains a collection - CSSRuleList, each of which corresponds to a rule in the stylesheet.  Each of those contains a cssText property holding the raw css:

document.styleSheets[x].cssRules[y].cssText

Loop through each css, then through each rule..

```
var docSheets = document.styleSheets;
for (i in docSheets) {
  for(j in docSheets[i].cssRules) {
   console.log(docSheets[i].cssRules[j].cssText);
  }
}
```

**Comment by nathanford** [comment]
Thanks @geekcubed. That worked, but the new properties don’t show up in the output:

```
body  {  }
h1 {  }
#site-header h2 {  }
p, li {  }
```

Tested in Firefox and Chrome.

**Comment by nathanford** [comment]
Adding some context to this conversation: type.js reads your CSS to find the new properties and then run functions based on those rules. Right now, it works well with on-page styles in a `style` tag. It can read external stylesheets, too, but in doing it requires an AJAX call to the sheet to read in the text. This can cause an extra download of CSS files.

What would be ideal is some way to read the stylesheet objects already loaded in the browser.

**Comment by 116-7** [comment]
I think you might have to stick to the solution you have at the moment. There is a cross domain issue that I wasn't aware of. You will see that the cssRules property is undefined. If you're lucky enough that the site is serving all of its CSS from it's own domain then you could use the proposed solution.

For example if you go to http://www.abc.net.au/news/ and run

```
for(var i in document.styleSheets[0].cssRules) { console.log(document.styleSheets[0].cssRules[i]); }
```

You will see a set of objects in your console, each containing a style attribute which will have the properties in a key => value map.

Whereas if you run that command on this very page it will likely fail or say undefined as the CSS on Github is served from their CDN domain.

I'd say you have the correct solution at the moment in terms of covering the most amount of use cases with the simplest code. Plus you are correct in leveraging the browser's cache so the request should be almost free.
